# Generated by Django 4.0.1 on 2022-11-15 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fechahorainicio', models.DateTimeField()),
                ('fechahorafin', models.DateTimeField()),
                ('estado', models.IntegerField()),
                ('link', models.URLField()),
                ('idagenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projectoapp.agenda')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=50)),
                ('fechacreacion', models.DateField()),
                ('estado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=50)),
                ('fechacreacion', models.DateField()),
                ('estado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=50)),
                ('fechacreacion', models.DateField()),
                ('estado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('idformapago', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=50)),
                ('fechacreacion', models.DateField()),
                ('estado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('idplataforma', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=50)),
                ('fechacreacion', models.DateField()),
                ('estado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=50)),
                ('fechacreacion', models.DateField()),
                ('estado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fechapago', models.DateField()),
                ('valor', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('comision', models.IntegerField()),
                ('idagenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projectoapp.agenda')),
                ('idformapago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projectoapp.formapago')),
                ('rutalumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projectoapp.alumno')),
            ],
        ),
        migrations.AddField(
            model_name='agenda',
            name='idasignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projectoapp.asignatura'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='idplataforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projectoapp.plataforma'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='idprofesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projectoapp.profesor'),
        ),
    ]
